import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { resolve } from 'path';
import { readdirSync, mkdirSync, copyFileSync } from 'fs';
import { tsExtensionFallback } from './scripts/vite-ts-fallback';

/** Copy publish artifacts that are not generated by Vite itself. */
const copyPublishAssetsPlugin = (): Plugin => ({
  name: 'copy-publish-assets',
  closeBundle() {
    mkdirSync('dist/themes', { recursive: true });
    readdirSync('src/styles')
      .filter(f => f.endsWith('.css'))
      .forEach(f => copyFileSync(`src/styles/${f}`, `dist/themes/${f}`));

    copyFileSync('src/index.d.ts', 'dist/index.d.ts');
  },
});

export default defineConfig({
  plugins: [react(), tsExtensionFallback(), copyPublishAssetsPlugin()],
  build: {
    lib: {
      entry: resolve(__dirname, 'src/index.ts'),
      name: 'WorksCalendar',
      formats: ['es', 'umd'],
      fileName: (format) => `works-calendar.${format}.js`,
    },
    rollupOptions: {
      external: ['react', 'react-dom', 'xlsx', '@supabase/supabase-js'],
      output: {
        globals: {
          react: 'React',
          'react-dom': 'ReactDOM',
        },
      },
    },
  },
});
